package.name = "reliq"
package.version = "0.1.0"
package.edition = "2024"
dependencies.paste.version = "*"
dependencies.modwire.version = "*"
dependencies.toga.version = "*"
dev-dependencies.criterion.version = "*"