package.name = "reliq"
package.version = "0.1.0"
package.edition = "2024"
package.keywords = [
    "no-panic"
]
dependencies.paste.version = "*"
dependencies.modwire.version = "*"
dependencies.toga.version = "*"
dependencies.rstest.version = "*"
dev-dependencies.criterion.version = "*"

features.default = [
    "unstable"
]
features.unstable = []

[[bench]]
name = "q"
harness = false

